import { Certificate } from "@meshsdk/core-cst";

export const metadata: { [assetName: string]: any } = {
    "Đỗ Viết Quang Huy": {
      name: "Đỗ Viết Quang Huy",
      image: "bafybeibls6tz7xkxlnfqxglb4p4zomhx6rpe4ta55l4hrtpyefh6qefamu",
      mediaType: "image/jpg",
      description: "You’ve successfully completed the Blockchain Basic course.",
      artist: "Blockchain Pioneer Student Club",
    },
    "Đỗ Đức Minh Quang": {
      name: "Đỗ Đức Minh Quang",
      image: "bafybeie4n6peuz42vhlqhwr2ojihzfn5mvgh2vdd367x7qyiwmqxahwdn4",
      mediaType: "image/jpg",
      description: "You’ve successfully completed the Blockchain Basic course.",
      artist: "Blockchain Pioneer Student Club",
    },
    "Phùng Thế Anh": {
      name: "Phùng Thế Anh",
      image: "bafybeid6rta66c2nnqjdvpg5xjrvyzn3gvocrve4airwobq37lmvghdlze",
      mediaType: "image/jpg",
      description: "You’ve successfully completed the Blockchain Basic course.",
      artist: "Blockchain Pioneer Student Club",
    },
    "Lê Phạm Thế Vũ": {
      name: "Lê Phạm Thế Vũ",
      image: "bafybeifxufmaj3xv6dwdb4zsoxtlsen4atgwc6clgfakf25cxl2qtol7wu",
      mediaType: "image/jpg",
      description: "You’ve successfully completed the Blockchain Basic course.",
      artist: "Blockchain Pioneer Student Club",
    },
    "Hoàng Văn Phong": {
      name: "Hoàng Văn Phong",
      image: "bafybeiagpelk5np4fpn3tiqxbrgknv3ovhvpxysw6c5zsjhi7gz4psqyey",
      mediaType: "image/jpg",
      description: "You’ve successfully completed the Blockchain Basic course.",
      artist: "Blockchain Pioneer Student Club",
    },
    "Phạm Ngọc Duy": {
      name: "Phạm Ngọc Duy",
      image: "bafybeihda4hpye6od374avzvtovdblohc5bhv5ofwerr5l5tcjivqfheei",
      mediaType: "image/jpg",
      description: "You’ve successfully completed the Blockchain Basic course.",
      artist: "Blockchain Pioneer Student Club",
    },
    "Vi Đình Sơn": {
      name: "Vi Đình Sơn",
      image: "bafybeicu73tslyplotmiwqrlgdmmjuiwgbnknoy3tunktrslirfd6ciepa",
      mediaType: "image/jpg",
      description: "You’ve successfully completed the Blockchain Basic course.",
      artist: "Blockchain Pioneer Student Club",
    },
    "Hoàng Thị Hải Vân": {
      name: "Hoàng Thị Hải Vân",
      image: "bafybeigbvjicifp43jltqs4jwgpm3c73e6zzws4a2jzo5h3lxgwilrnrei",
      mediaType: "image/jpg",
      description: "You’ve successfully completed the Blockchain Basic course.",
      artist: "Blockchain Pioneer Student Club",
    },
    "Nguyễn Văn Năng": {
      name: "Nguyễn Văn Năng",
      image: "bafybeig4mdaj4opfr7wmna7gycpbkoaha6a3xjkq6mvqqg5pgpxc4sejyu",
      mediaType: "image/jpg",
      description: "You’ve successfully completed the Blockchain Basic course.",
      artist: "Blockchain Pioneer Student Club",
    },
    "Lương Thế Anh": {
      name: "Lương Thế Anh",
      image: "bafybeibh7k5qcs4wz7wjv5xrcepx7hmwr6qo26j6wxxsascivpmlxlwho4",
      mediaType: "image/jpg",
      description: "You’ve successfully completed the Blockchain Basic course.",
      artist: "Blockchain Pioneer Student Club",
    },
    "Bùi Đức Mạnh": {
      name: "Bùi Đức Mạnh",
      image: "bafybeig7quvquagoocktgrbqqbhborwdljor3u6u7kyc54tssowfoftnpa",
      mediaType: "image/jpg",
      description: "You’ve successfully completed the Blockchain Basic course.",
      artist: "Blockchain Pioneer Student Club",
    },
    "Trần Thị Hồng Nhung": {
      name: "Trần Thị Hồng Nhung",
      image: "bafybeihmi73waahfa7qklokrjolgm4r45cs6sjeem5f76qazvr2a7ulo54",
      mediaType: "image/jpg",
      description: "You’ve successfully completed the Blockchain Basic course.",
      artist: "Blockchain Pioneer Student Club",
    },
    "Bùi Hương Giang": {
      name: "Bùi Hương Giang",
      image: "bafybeicicg6d2vvm2cnjqucjnpqxhn4dbzrpwuw2e2ye3wivdnngzna7uq",
      mediaType: "image/jpg",
      description: "You’ve successfully completed the Blockchain Basic course.",
      artist: "Blockchain Pioneer Student Club",
    },
    "Lý Đức Hiếu": {
      name: "Lý Đức Hiếu",
      image: "bafybeidkvgcotxl3b7w4myjub3gzg3nsxv7jehpkcpogd7ywyxjsimvd3y",
      mediaType: "image/jpg",
      description: "You’ve successfully completed the Blockchain Basic course.",
      artist: "Blockchain Pioneer Student Club",
    },
    "Phùng Nguyễn Trọng An": {
      name: "Phùng Nguyễn Trọng An",
      image: "bafybeiaslg7jxtug6afmmecikps32g2j72kzqq6skapbfj2iuygx44omyu",
      mediaType: "image/jpg",
      description: "You’ve successfully completed the Blockchain Basic course.",
      artist: "Blockchain Pioneer Student Club",
    },
  };